#!/usr/bin/env python3
"""OFFICIAL R5 restart-recovery data collection -- 30 blocks x 2 arms = 60
trials, per the approved plan (01_DAIM_OS_Implementation/
R5_RESTART_RECOVERY_PROTOCOL.md, Section 8 sign-off). Reads the frozen,
pre-registered schedule from r5_official_schedule.json (generated by
r5_generate_schedule.py, seed 20260929, saved before this script ever
ran) -- the order is not generated here, only followed.

Recovery window: 30 seconds (changed from the 15s used during the
feasibility dry-run; documented explicitly, not silently).

Every trial's full result is appended to the output file as it
completes, including invalid/failed trials -- nothing is dropped or
replaced. If this script is interrupted, it can be re-run; already-
recorded blocks are skipped (see --resume logic below) so a restart
does not duplicate or lose trials.
"""
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from r5_restart_recovery_feasibility import run_trial, _self_test_parser  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SCHEDULE_PATH = ROOT / "results/network/r5_official_schedule.json"
RECOVER_WINDOW_S = 30


def load_schedule():
    schedule = json.loads(SCHEDULE_PATH.read_text())
    assert schedule["recover_window_s"] == RECOVER_WINDOW_S, "schedule/runner window mismatch"
    return schedule


def load_completed(out_path):
    """(block, arm) pairs already present in the output file, so a
    re-run after an interruption resumes rather than duplicates."""
    done = set()
    if out_path.exists():
        with out_path.open() as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                r = json.loads(line)
                done.add((r["block"], r["mode"]))
    return done


def main():
    _self_test_parser()
    print("ping parser self-test: PASS", flush=True)

    schedule = load_schedule()
    out_path = ROOT / "results/network/r5_official_sample.jsonl"
    completed = load_completed(out_path)
    print(f"schedule: {schedule['n_blocks']} blocks, seed={schedule['seed']}, "
          f"window={schedule['recover_window_s']}s, already completed={len(completed)}", flush=True)

    with out_path.open("a") as f:
        for block in schedule["blocks"]:
            for arm in block["order"]:
                key = (block["block"], arm)
                if key in completed:
                    print(f"=== block {block['block']} {arm}: already recorded, skipping ===", flush=True)
                    continue
                print(f"=== block {block['block']} {arm} === {time.strftime('%Y-%m-%d %H:%M:%S')}", flush=True)
                r = run_trial(arm, block["block"], recover_window_s=RECOVER_WINDOW_S)
                r["block"] = block["block"]
                f.write(json.dumps(r) + "\n")
                f.flush()
                status = "valid" if r["valid_for_inference"] else f"INVALID: {r['invalidation_reasons']}"
                recovered = r.get("connectivity_recovery_observed")
                t_rec = r.get("connectivity_recovery_time_from_restart_s")
                print(f"    -> {status}; recovered={recovered}; "
                      f"recovery_time_from_restart_s={t_rec}", flush=True)

    print(out_path)


if __name__ == "__main__":
    main()
